{{- if and .Values.enabled .Values.superuser.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-cnpg-admin-creds" .Release.Name | trunc 63 | trimSuffix "-" | quote }}
type: kubernetes.io/basic-auth
stringData:
  password: {{ randAlphaNum 16 | quote }}
{{- end }}
